---
deployment:
 tasks:
  - export REPOPATH=/home/inmainl1/repositories/XCwebpage/
  - export DEPLOYPATH=/home/inmainl1/public_html/
  - /bin/cp -R $REPOPATH/blog_doc $DEPLOYPATH/blog_doc
  - /bin/cp -R $REPOPATH/fonts $DEPLOYPATH/fonts
