---
deployment:
 tasks:
  - export REPOPATH=/home/inmainl1/repositories/XCwebpage/
  - export DEPLOYPATH=/home/inmainl1/public_html/
  - rsync -rav --exclude '.git' --exclude '.cpanel.yml' --exclude setup_doc --del $REPOPATH $DEPLOYPATH
